[package]
name = "healthz"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.36", features = ["realloc"] }
wit-bindgen-rt = "0.33.0"

[package.metadata.component]
package = "component:healthz"
